spring:
  datasource:
    url: jdbc:mysql://localhost/security_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: jefferey12
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.bdf63f0b08d4c4ab
            clientSecret: cc1bd0fbea9defe560f10006ba9b78c749c4312e



#  spring:
#    security:
#      oauth2:
#        client:
#          registration:
#            github:
#              clientId: Iv1.bdf63f0b08d4c4ab
#              clientSecret: cc1bd0fbea9defe560f10006ba9b78c749c4312e
#              accessTokenUri: http://github.com/login/oauth/access_token
#              userAuthorizationUri: http://github.com/login/oauth/authorize
#              clientAuthenticationScheme: form
#              tokenName: oauth_token
#              autheticationScheme: query
#        resource:
#          userInfoUri: https://api.github.com/user
logging:
  level: debug
