version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
steps:
  - run:
      name: Send to Codecov
      command: bash <(curl -s https://codecov.io/bash)